<table class="table table-hover">
    <thead>
        <tr>
            <th>#</th>
            <th>Nombre</th>
            <th>Pago esta semana?</th>
            <th>Apodo</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>1</td>
            <td>Saúl</td>
            <td>NO</td>
            <td>@peditos</td>
        </tr>
        <tr>
            <td>2</td>
            <td>Marck</td>
            <td>NO</td>
            <td>@fannys</td>
        </tr>
        <tr>
            <td>3</td>
            <td>Anakin</td>
            <td>NO</td>
            <td>@dianillo</td>
        </tr>
        <tr>
            <td>4</td>
            <td>Bambi</td>
            <td>NO</td>
            <td>@tamaro</td>
        </tr>
        <tr>
            <td>5</td>
            <td>Byron</td>
            <td>NO</td>
            <td>@marrufito</td>
        </tr>
        <tr>
            <td>6</td>
            <td>Ñongas</td>
            <td>NO</td>
            <td>@anti-mojo</td>
        </tr>
        <tr>
            <td>7</td>
            <td>Cawa</td>
            <td>NO</td>
            <td>@tragaldabas</td>
            </tr>
        <tr>
            <td>8</td>
            <td>Camarillo</td>
            <td>NO</td>
            <td>@tatismeama</td>
        </tr>
    </tbody>
</table>